# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取最新代码
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      # 缓存Flutter SDK
      - name: Prepare Flutter pub-cache
        run: mkdir -p ~/.flutter
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-3.35.4
      # 配置flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'
          cache: true
      # 缓存flutter pub 依赖
      - name: Prepare Flutter pub-cache
        run: mkdir -p ~/.pub-cache
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
      # 缓存gradle
      - name: Prepare Gradle cache
        run: mkdir -p ~/.gradle/caches ~/.gradle/wrapper/
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      # 更新依赖
      - run: flutter pub get
      # 提取版本号
      - name: read flutter version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
      # 打包
      - run: flutter build apk --release --target-platform android-arm64,android-arm --split-per-abi
      - name: Create a release apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{secrets.TOKEN}}
          tag: "v${{env.GITHUB_ENV}}-build${{github.run_number}}"